spring:
  application:
    name: test_block
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/hapiweb
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 5
        min-idle: 0
    timeout: 10000

server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/**/*Mapper.xml

